import BackToHome from "../component/BackToHome";
import "../assignments/ASG_51.css";
import { useState, useEffect, useRef } from "react";

export default function ASG_51() {
  const [section, setSection] = useState(0);
  const [sectionsCount, setSectionsCount] = useState(0);
  const [mobileReversed, setMobileReversed] = useState(false);

  const sectionsRef = useRef(null);
  const reversedRef = useRef([]);
  const scrollLockRef = useRef(false);
  const timeoutRef = useRef(0);

  useEffect(() => {
    const el = sectionsRef.current;
    if (!el) return;
    const nodes = Array.from(el.querySelectorAll(".section-asg51"));
    setSectionsCount(nodes.length);
    reversedRef.current = nodes.map((n) => n.getAttribute("data-reversed") === "true");
    setMobileReversed(reversedRef.current[0] ?? false);
    return () => {
      if (timeoutRef.current) clearTimeout(timeoutRef.current);
    };
  }, []);

  useEffect(() => {
    setMobileReversed(reversedRef.current[section] ?? false);
  }, [section]);

  const lockAndDelay = (cb) => {
    if (scrollLockRef.current) return;
    scrollLockRef.current = true;
    cb();
    clearTimeout(timeoutRef.current);
    timeoutRef.current = setTimeout(() => {
      scrollLockRef.current = false;
    }, 700); 
  };

  const goPrev = () =>
    lockAndDelay(() => setSection((s) => Math.max(0, s - 1)));
  const goNext = () =>
    lockAndDelay(() => setSection((s) => Math.min(sectionsCount - 1, s + 1)));

  const handleWheel = (e) => {
    // deltaY > 0 = scroll down, < 0 = scroll up
    if (e.deltaY > 0) goNext();
    else if (e.deltaY < 0) goPrev();
  };

  return (
    <div className="asg51">
      <BackToHome />
      <div className="container-asg51" onWheel={handleWheel}>
        <div className="hint-asg51">Use Mouse Wheel or Touchpad to scroll through sections</div>
        <div
          className="arrow-asg51 arrow-up-asg51"
          style={{backgroundImage: "url(./asg51/step-scroll-animation-up.svg)"}}
          data-hidden={section === 0 ? "true" : "false"}
          onClick={goPrev}
        ></div>
        <div
          className="arrow-asg51 arrow-down-asg51"
          style={{ backgroundImage: "url(./asg51/step-scroll-animation-down.svg)"}}
          data-hidden={section === sectionsCount - 1 ? "true" : "false"}
          onClick={goNext}
        ></div>
        <div 
          className="mobile-asg51"
          style={{backgroundImage : "url(./asg51/step-scroll-animation.png)"}} 
          data-reversed={mobileReversed ? "true" : "false"}
        ></div>
        <div className="sections-asg51" data-section={section} ref={sectionsRef}>
          {/* Internet of Things (phone on right) */}
          <div className="section-asg51" data-reversed="false">
            <div className="section-content-asg51">
              <div className="section-title-asg51">Internet of Things</div>
              <div className="section-description-asg51">
                <div className="section-paragraph-asg51">
                  The Internet of Things (IoT) is a network of physical devices embedded with sensors, software, and connectivity features that allow them to collect and exchange data.
                </div>
                <div className="section-paragraph-asg51">
                  IoT devices range from household appliances like smart refrigerators and thermostats to industrial machines and environmental monitoring systems.
                </div>
                <div className="section-paragraph-asg51">
                  By enabling real-time data collection and analysis, IoT improves efficiency, enhances user convenience, and supports automation in various sectors including healthcare, agriculture, and manufacturing.
                </div>
                <div className="section-paragraph-asg51">
                  Despite its benefits, IoT raises concerns over cybersecurity, data privacy, and the management of the vast amounts of information generated by connected devices.
                </div>
              </div>
            </div>
          </div>

          {/* Blockchain Technology (phone on left) */}
          <div className="section-asg51" data-reversed="true">
            <div className="section-content-asg51">
              <div className="section-title-asg51">Blockchain Technology</div>
              <div className="section-description-asg51">
                <div className="section-paragraph-asg51">
                  Blockchain is a distributed and immutable ledger technology that records transactions across a network of computers, ensuring transparency and security without relying on a central authority.
                </div>
                <div className="section-paragraph-asg51">
                  Each block contains a list of transactions, and once added to the chain, the data cannot be altered, making it highly resistant to fraud and hacking.
                </div>
                <div className="section-paragraph-asg51">
                  Although best known for powering cryptocurrencies like Bitcoin and Ethereum, blockchain applications extend to supply chain management, secure identity verification, and voting systems.
                </div>
                <div className="section-paragraph-asg51">
                  The technology still faces challenges such as high energy consumption in some consensus mechanisms and scalability issues that limit its widespread adoption.
                </div>
              </div>
            </div>
          </div>

          {/* Artificial Intelligence (phone on right) */}
          <div className="section-asg51" data-reversed="false">
            <div className="section-content-asg51">
              <div className="section-title-asg51">Artificial Intelligence</div>
              <div className="section-description-asg51">
                <div className="section-paragraph-asg51">
                  "Artificial Intelligence (AI) refers to the development of computer systems capable of performing tasks that usually require human intelligence, such as visual perception, speech recognition, and decision-making."
                </div>
                <div className="section-paragraph-asg51">
                  "Machine learning, a subset of AI, enables systems to learn and improve from experience without being explicitly programmed, making it the driving force behind many modern AI applications."
                </div>
                <div className="section-paragraph-asg51">
                  "AI is used in diverse areas like healthcare for disease diagnosis, finance for fraud detection, and transportation for self-driving vehicles, revolutionizing industries and improving efficiency."
                </div>
                <div className="section-paragraph-asg51">
                  "While AI brings numerous benefits, it also raises ethical concerns regarding data privacy, bias in algorithms, and the potential displacement of human jobs in certain sectors."
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
